# Generated by Django 4.0.1 on 2022-01-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_body_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug_title',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
